### PR TITLE
Move preference icon margin to icon element instead of main container

### PR DESCRIPTION
**Pull request by pedrodanielcsantos**

### CODE REVIEW

**Comment by rastislavvasko** [comment]
I remember now why we have a simplified version (with regards to the icon) of [preference_material.xml](https://github.com/android/platform_frameworks_base/blob/master/core/res/res/layout/preference_material.xml). We don't have the wrapping `LinearLayout`, because it has an internal id and `Preference` uses it to hide the wrapper if the icon is missing. We'd have to subclass `Preference` and recreate the whole hierarchy, which was quite overkill at that point (because we didn't even need the icons anywhere).

I'm saying that, because with `android:layout_marginEnd="32dp"` we will only follow the 72dp vertical keyline as long as our icons are 24dp (16dp root's start padding, 24dp icon width and 32dp icon end margin).

Maybe we could try this:
```xml
<ImageView
    android:id="@android:id/icon"
    android:layout_width="56dp"
    android:layout_height="wrap_content"
    android:layout_gravity="center"
    android:maxHeight="56dp"
    android:scaleType="fitStart" />
```

It shouldn't scale the icon as the height is `wrap_content`, but we have the width fixed to 56dp so that with the root's padding the text will start at 72dp.

**Comment by pedrodanielcsantos** [comment]
Awesome tip Rasto, thanks a lot! 👏 Addressed it here: https://github.com/Doist/AndroidMaterial/pull/18/commits/d2f6ebef26f61f4a7fc88489d1228b684cbb11cd

**Comment by rastislavvasko** [comment]
No problem, looks good! 👍

**Comment by pedrodanielcsantos** [comment]
Thanks for the review Rasto! Merging now.

**Pull request merged**
