### PR TITLE
Add padding to preference cell between icon and text

### PR DESCRIPTION
**Pull request by pedrodanielcsantos**

### CODE REVIEW

**Comment by goncalossilva** [comment]
The formatting of copyright notices are broken, but otherwise all looks great. I see this has always been in `data/res/layout/preference_material.xml`. Unsure why we didn't have it here in the first place.

**Comment by pedrodanielcsantos** [comment]
@goncalossilva fixed the copyright alignment. Please let me know if it's ok to merge please 👍 And thanks a lot for the review!

**Comment by goncalossilva** [comment]
All good to merge!

**Comment by pedrodanielcsantos** [comment]
Thanks a lot! 🥂 Merging!

**Pull request merged**
